/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.views;

import br.edu.imepac.views.especialidade.CadastrarEspecialidade;
import br.edu.imepac.views.funcionario.AtualizarFuncionario;
import br.edu.imepac.views.funcionario.CadastrarFuncionario;

/**
 *
 * @author 231-001278
 */
public class DesktopMain extends javax.swing.JFrame {

    /**
     * Creates new form DesktopMain
     */
    public DesktopMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupFuncionario = new javax.swing.JPopupMenu();
        inserirFuncionarioItem = new javax.swing.JMenuItem();
        alterarFuncionarioItem = new javax.swing.JMenuItem();
        popupEspecialidade = new javax.swing.JPopupMenu();
        cadastrarEspecialidadeItem = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        adminMenu = new javax.swing.JMenu();
        funcionarioItem = new javax.swing.JMenuItem();
        usuariosItem = new javax.swing.JMenuItem();
        medicosItem = new javax.swing.JMenuItem();
        especialidadesItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        inserirFuncionarioItem.setText("Cadastrar Funcionario");
        inserirFuncionarioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirFuncionarioItemActionPerformed(evt);
            }
        });
        popupFuncionario.add(inserirFuncionarioItem);

        alterarFuncionarioItem.setText("Listar/Editar usuários");
        alterarFuncionarioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFuncionarioItemActionPerformed(evt);
            }
        });
        popupFuncionario.add(alterarFuncionarioItem);

        cadastrarEspecialidadeItem.setSelected(true);
        cadastrarEspecialidadeItem.setText("Cadastrar Especialidade");
        cadastrarEspecialidadeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEspecialidadeItemActionPerformed(evt);
            }
        });
        popupEspecialidade.add(cadastrarEspecialidadeItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminMenu.setText("Administração");
        adminMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMenuMouseEntered(evt);
            }
        });

        funcionarioItem.setText("Funcionarios");
        funcionarioItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                funcionarioItemMouseEntered(evt);
            }
        });
        funcionarioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioItemActionPerformed(evt);
            }
        });
        adminMenu.add(funcionarioItem);

        usuariosItem.setText("Usuários");
        adminMenu.add(usuariosItem);

        medicosItem.setText("Médicos");
        medicosItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicosItemActionPerformed(evt);
            }
        });
        adminMenu.add(medicosItem);

        especialidadesItem.setText("Especialidades");
        especialidadesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadesItemActionPerformed(evt);
            }
        });
        adminMenu.add(especialidadesItem);

        jMenuBar1.add(adminMenu);

        jMenu1.setText("Agendamento");
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Atendimento");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void adminMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMenuMouseEntered
        
// TODO add your handling code here:
    }//GEN-LAST:event_adminMenuMouseEntered

    private void funcionarioItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionarioItemMouseEntered
        
    }//GEN-LAST:event_funcionarioItemMouseEntered

    private void funcionarioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioItemActionPerformed
        popupFuncionario.show(this, funcionarioItem.getX()+100, funcionarioItem.getY()+50);
    }//GEN-LAST:event_funcionarioItemActionPerformed

    private void inserirFuncionarioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirFuncionarioItemActionPerformed
        new CadastrarFuncionario().setVisible(true);
    }//GEN-LAST:event_inserirFuncionarioItemActionPerformed

    private void alterarFuncionarioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFuncionarioItemActionPerformed
        new AtualizarFuncionario().setVisible(true);
    }//GEN-LAST:event_alterarFuncionarioItemActionPerformed

    private void medicosItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicosItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medicosItemActionPerformed

    private void cadastrarEspecialidadeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEspecialidadeItemActionPerformed
        new CadastrarEspecialidade().setVisible(true);
    }//GEN-LAST:event_cadastrarEspecialidadeItemActionPerformed

    private void especialidadesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadesItemActionPerformed
        popupEspecialidade.show(this,especialidadesItem.getX()+100, especialidadesItem.getY()+50);
    }//GEN-LAST:event_especialidadesItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesktopMain().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adminMenu;
    private javax.swing.JMenuItem alterarFuncionarioItem;
    private javax.swing.JCheckBoxMenuItem cadastrarEspecialidadeItem;
    private javax.swing.JMenuItem especialidadesItem;
    private javax.swing.JMenuItem funcionarioItem;
    private javax.swing.JMenuItem inserirFuncionarioItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem medicosItem;
    private javax.swing.JPopupMenu popupEspecialidade;
    private javax.swing.JPopupMenu popupFuncionario;
    private javax.swing.JMenuItem usuariosItem;
    // End of variables declaration//GEN-END:variables
}
