/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.views;

import br.edu.imepac.entidades.Usuario;
import br.edu.imepac.views.especialidade.AtualizarEspecialidade;
import br.edu.imepac.views.especialidade.CadastrarEspecialidade;
import br.edu.imepac.views.funcionario.AtualizarFuncionario;
import br.edu.imepac.views.funcionario.CadastrarFuncionario;
import br.edu.imepac.views.medico.AtualizarMedico;
import br.edu.imepac.views.medico.CadastroMedico;

/**
 *
 * @author 231-001278
 */
public class DesktopMain extends javax.swing.JFrame {

    /**
     * Creates new form DesktopMain
     */
    public DesktopMain() {
        initComponents();
        adminMenu.setEnabled(false);
        agendamentoMenu.setEnabled(false);
        atendimentoMenu.setEnabled(false);
    }
    public DesktopMain(Usuario user){
        initComponents();
        allowPrivileges(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupFuncionario = new javax.swing.JPopupMenu();
        inserirFuncionarioItem = new javax.swing.JMenuItem();
        alterarFuncionarioItem = new javax.swing.JMenuItem();
        popupEspecialidade = new javax.swing.JPopupMenu();
        cadastrarEspecialidadeItem = new javax.swing.JMenuItem();
        alterarEspecialidadeItem = new javax.swing.JMenuItem();
        popupMedico = new javax.swing.JPopupMenu();
        cadastrarMedicoItem = new javax.swing.JMenuItem();
        atualizarMedicoItem = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        adminMenu = new javax.swing.JMenu();
        funcionarioItem = new javax.swing.JMenuItem();
        usuariosItem = new javax.swing.JMenuItem();
        medicosItem = new javax.swing.JMenuItem();
        especialidadesItem = new javax.swing.JMenuItem();
        agendamentoMenu = new javax.swing.JMenu();
        atendimentoMenu = new javax.swing.JMenu();

        inserirFuncionarioItem.setText("Cadastrar Funcionario");
        inserirFuncionarioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirFuncionarioItemActionPerformed(evt);
            }
        });
        popupFuncionario.add(inserirFuncionarioItem);

        alterarFuncionarioItem.setText("Listar/Editar usuários");
        alterarFuncionarioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFuncionarioItemActionPerformed(evt);
            }
        });
        popupFuncionario.add(alterarFuncionarioItem);

        cadastrarEspecialidadeItem.setText("Cadastrar Especialidade");
        cadastrarEspecialidadeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarEspecialidadeItemActionPerformed(evt);
            }
        });
        popupEspecialidade.add(cadastrarEspecialidadeItem);

        alterarEspecialidadeItem.setText("Editar Especialidade");
        alterarEspecialidadeItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarEspecialidadeItemActionPerformed(evt);
            }
        });
        popupEspecialidade.add(alterarEspecialidadeItem);

        cadastrarMedicoItem.setText("Cadastrar Medicos");
        cadastrarMedicoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarMedicoItemActionPerformed(evt);
            }
        });
        popupMedico.add(cadastrarMedicoItem);

        atualizarMedicoItem.setText("Atualizar Medicos");
        atualizarMedicoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarMedicoItemActionPerformed(evt);
            }
        });
        popupMedico.add(atualizarMedicoItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminMenu.setText("Administração");
        adminMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMenuMouseEntered(evt);
            }
        });

        funcionarioItem.setText("Funcionarios");
        funcionarioItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                funcionarioItemMouseEntered(evt);
            }
        });
        funcionarioItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionarioItemActionPerformed(evt);
            }
        });
        adminMenu.add(funcionarioItem);

        usuariosItem.setText("Usuários");
        adminMenu.add(usuariosItem);

        medicosItem.setText("Médicos");
        medicosItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicosItemActionPerformed(evt);
            }
        });
        adminMenu.add(medicosItem);

        especialidadesItem.setText("Especialidades");
        especialidadesItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especialidadesItemActionPerformed(evt);
            }
        });
        adminMenu.add(especialidadesItem);

        jMenuBar1.add(adminMenu);

        agendamentoMenu.setText("Agendamento");
        jMenuBar1.add(agendamentoMenu);

        atendimentoMenu.setText("Atendimento");
        atendimentoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atendimentoMenuActionPerformed(evt);
            }
        });
        jMenuBar1.add(atendimentoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void atendimentoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atendimentoMenuActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_atendimentoMenuActionPerformed
    private void allowPrivileges(Usuario user){
        if(user.getModulo_administrativo().equals("n")) {
            adminMenu.setEnabled(false);
        }else{
            if(user.getCadastro_funcionario().equals("n"))
                funcionarioItem.setEnabled(false);
            if(user.getCadastro_especialidade().equals("n"))
                especialidadesItem.setEnabled(false);
            if(user.getCadastro_medico().equals("n"))
                medicosItem.setEnabled(false);
            if(user.getCadastro_usuario().equals("n"))
                usuariosItem.setEnabled(false);
        }

        if(user.getModulo_agendamento().equals("n")){
            agendamentoMenu.setEnabled(false);
        }
        if(user.getModulo_atendimento().equals("n")){
            atendimentoMenu.setEnabled(false);
        }

    }
    private void adminMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMenuMouseEntered
        
// TODO add your handling code here:
    }//GEN-LAST:event_adminMenuMouseEntered

    private void funcionarioItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionarioItemMouseEntered
        
    }//GEN-LAST:event_funcionarioItemMouseEntered

    private void funcionarioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionarioItemActionPerformed
        popupFuncionario.show(this, funcionarioItem.getX()+100, funcionarioItem.getY()+50);
    }//GEN-LAST:event_funcionarioItemActionPerformed

    private void inserirFuncionarioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirFuncionarioItemActionPerformed
        new CadastrarFuncionario().setVisible(true);
    }//GEN-LAST:event_inserirFuncionarioItemActionPerformed

    private void alterarFuncionarioItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFuncionarioItemActionPerformed
        new AtualizarFuncionario().setVisible(true);
    }//GEN-LAST:event_alterarFuncionarioItemActionPerformed

    private void medicosItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicosItemActionPerformed
        popupMedico.show(this,medicosItem.getX()+100, medicosItem.getY()+50);
    }//GEN-LAST:event_medicosItemActionPerformed

    private void especialidadesItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especialidadesItemActionPerformed
        popupEspecialidade.show(this,especialidadesItem.getX()+100, especialidadesItem.getY()+50);
    }//GEN-LAST:event_especialidadesItemActionPerformed

    private void alterarEspecialidadeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarEspecialidadeItemActionPerformed
        new AtualizarEspecialidade().setVisible(true);
    }//GEN-LAST:event_alterarEspecialidadeItemActionPerformed

    private void cadastrarEspecialidadeItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarEspecialidadeItemActionPerformed
        new CadastrarEspecialidade().setVisible(true);
    }//GEN-LAST:event_cadastrarEspecialidadeItemActionPerformed

    private void cadastrarMedicoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarMedicoItemActionPerformed
        new CadastroMedico().setVisible(true);
    }//GEN-LAST:event_cadastrarMedicoItemActionPerformed

    private void atualizarMedicoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarMedicoItemActionPerformed
        new AtualizarMedico().setVisible(true);
    }//GEN-LAST:event_atualizarMedicoItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DesktopMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DesktopMain().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu adminMenu;
    private javax.swing.JMenu agendamentoMenu;
    private javax.swing.JMenuItem alterarEspecialidadeItem;
    private javax.swing.JMenuItem alterarFuncionarioItem;
    private javax.swing.JMenu atendimentoMenu;
    private javax.swing.JMenuItem atualizarMedicoItem;
    private javax.swing.JMenuItem cadastrarEspecialidadeItem;
    private javax.swing.JMenuItem cadastrarMedicoItem;
    private javax.swing.JMenuItem especialidadesItem;
    private javax.swing.JMenuItem funcionarioItem;
    private javax.swing.JMenuItem inserirFuncionarioItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem medicosItem;
    private javax.swing.JPopupMenu popupEspecialidade;
    private javax.swing.JPopupMenu popupFuncionario;
    private javax.swing.JPopupMenu popupMedico;
    private javax.swing.JMenuItem usuariosItem;
    // End of variables declaration//GEN-END:variables
}
