/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.views.usuario;

import br.edu.imepac.controladores.UsuarioController;
import br.edu.imepac.entidades.Usuario;
import br.edu.imepac.utils.IRolesForms;
import br.edu.imepac.views.BaseForm;

/**
 *
 * @author vitoraugustobarcelospovoa
 */
public class CadastrarUsuario extends BaseForm implements IRolesForms<Usuario> {
    UsuarioController usuarioController;
    /**
     * Creates new form CadastrodoUsuário
     */
    public CadastrarUsuario() {
        initComponents();
        usuarioController = new UsuarioController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        adminCheckBox = new javax.swing.JCheckBox();
        agendaCheckBox = new javax.swing.JCheckBox();
        atendimentoCheckBox = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        funcionarioCheckBox = new javax.swing.JCheckBox();
        usuarioCheckBox = new javax.swing.JCheckBox();
        pacienteCheckBox = new javax.swing.JCheckBox();
        especialidadeCheckBox = new javax.swing.JCheckBox();
        medicoCheckBox = new javax.swing.JCheckBox();
        convenioCheckBox = new javax.swing.JCheckBox();
        agendamentoCheckBox = new javax.swing.JCheckBox();
        cancelamentoCheckBox = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Roboto Condensed", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro Usuário");

        jLabel17.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Senha");

        jLabel13.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Nome do Usuário");

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Confirmar Senha");

        adminCheckBox.setText("Administração");
        adminCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCheckBoxActionPerformed(evt);
            }
        });

        agendaCheckBox.setText("Agendamento");
        agendaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agendaCheckBoxActionPerformed(evt);
            }
        });

        atendimentoCheckBox.setText("Atendimento");

        funcionarioCheckBox.setText("Funcionario");
        funcionarioCheckBox.setEnabled(false);

        usuarioCheckBox.setText("Usuario");
        usuarioCheckBox.setEnabled(false);
        usuarioCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCheckBoxActionPerformed(evt);
            }
        });

        pacienteCheckBox.setText("Paciente");
        pacienteCheckBox.setEnabled(false);

        especialidadeCheckBox.setText("Especialidade");
        especialidadeCheckBox.setEnabled(false);

        medicoCheckBox.setText("Medico");
        medicoCheckBox.setEnabled(false);

        convenioCheckBox.setText("Convenio");
        convenioCheckBox.setEnabled(false);

        agendamentoCheckBox.setText("Agendar Consulta");
        agendamentoCheckBox.setEnabled(false);

        cancelamentoCheckBox.setText("Cancelamento Consulta");
        cancelamentoCheckBox.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Roboto Condensed", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Nome do Usuário");

        jLabel2.setText("Módulos");

        jLabel3.setText("Especificos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jSeparator1)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(adminCheckBox)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(agendaCheckBox)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(atendimentoCheckBox)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(funcionarioCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(usuarioCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(convenioCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(especialidadeCheckBox))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(medicoCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pacienteCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(agendamentoCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cancelamentoCheckBox)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 18, Short.MAX_VALUE))
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(jLabel18)
                        .addGap(9, 9, 9)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adminCheckBox)
                            .addComponent(agendaCheckBox)
                            .addComponent(atendimentoCheckBox)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funcionarioCheckBox)
                    .addComponent(usuarioCheckBox)
                    .addComponent(especialidadeCheckBox)
                    .addComponent(jLabel3)
                    .addComponent(convenioCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(medicoCheckBox)
                    .addComponent(agendamentoCheckBox)
                    .addComponent(cancelamentoCheckBox)
                    .addComponent(jButton1)
                    .addComponent(pacienteCheckBox))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioCheckBoxActionPerformed

    private void adminCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCheckBoxActionPerformed
        autocheck();
    }//GEN-LAST:event_adminCheckBoxActionPerformed
    private void autocheck(){
        if(agendaCheckBox.isSelected()){
            pacienteCheckBox.setEnabled(true);
            agendamentoCheckBox.setEnabled(true);
            cancelamentoCheckBox.setEnabled(true);
        }else{
            pacienteCheckBox.setEnabled(false);
            agendamentoCheckBox.setEnabled(false);
            cancelamentoCheckBox.setEnabled(false);
            pacienteCheckBox.setSelected(false);
            agendamentoCheckBox.setSelected(false);
            cancelamentoCheckBox.setSelected(false);
        }
        if(adminCheckBox.isSelected()){
            funcionarioCheckBox.setEnabled(true);
            medicoCheckBox.setEnabled(true);
            especialidadeCheckBox.setEnabled(true);
            convenioCheckBox.setEnabled(true);
            usuarioCheckBox.setEnabled(true);
        }else{
            funcionarioCheckBox.setEnabled(false);
            funcionarioCheckBox.setSelected(false);
            medicoCheckBox.setEnabled(false);
            funcionarioCheckBox.setSelected(false);
            especialidadeCheckBox.setSelected(false);
            especialidadeCheckBox.setEnabled(false);
            convenioCheckBox.setEnabled(false);
            convenioCheckBox.setSelected(false);
            usuarioCheckBox.setEnabled(false);
            usuarioCheckBox.setSelected(false);
        }
    }
    private void agendaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agendaCheckBoxActionPerformed
        autocheck();
    }//GEN-LAST:event_agendaCheckBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(isFieldsFormsValidate()){
            this.usuarioController.addUsuario(createEntityViewRepresentation());
            this.showSuccessMessage("Usuario cadastrado com sucesso");
            this.clearFields();
            autocheck();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearFields(){
        jTextField8.setText("");
        jTextField1.setText("");
        jTextField2.setText("");
        adminCheckBox.setSelected(false);
        agendaCheckBox.setSelected(false);
        atendimentoCheckBox.setSelected(false);
    }
    @Override
    public Usuario createEntityViewRepresentation() {
        String funcionario, usuario, medico, convenio, especialidade, paciente, agendar, cancelar, mAdmin, mAgen, mAten;
        if(usuarioCheckBox.isSelected()) usuario = "y"; else usuario = "n";
        if(funcionarioCheckBox.isSelected()) funcionario = "y"; else funcionario = "n";
        if(medicoCheckBox.isSelected()) medico = "y"; else medico = "n";
        if(convenioCheckBox.isSelected()) convenio = "y"; else convenio = "n";
        if(especialidadeCheckBox.isSelected()) especialidade = "y"; else especialidade = "n";
        if(pacienteCheckBox.isSelected()) paciente = "y"; else paciente = "n";
        if(agendamentoCheckBox.isSelected()) agendar = "y"; else agendar = "n";
        if(cancelamentoCheckBox.isSelected()) cancelar = "y"; else cancelar = "n";
        if(adminCheckBox.isSelected()) mAdmin = "y"; else mAdmin = "n";
        if(agendaCheckBox.isSelected())mAgen = "y"; else mAgen = "n";
        if(atendimentoCheckBox.isSelected()) mAten = "y"; else mAten = "n";

        return new Usuario(
                jTextField8.getText(),
                jTextField1.getText(),
                funcionario,
                usuario,
                paciente,
                especialidade,
                medico,
                convenio,
                agendar,
                cancelar,
                mAdmin,
                mAgen,
                mAten
        );
    }

    @Override
    public boolean isFieldsFormsValidate() {
        if(jTextField8.getText().isBlank() || jTextField8.getText().isEmpty()){
            this.showWarningMessage("Preencha o id do usuario!");
            return false;
        }
        if(jTextField1.getText().isBlank() || jTextField1.getText().isEmpty()){
            this.showWarningMessage("Insira uma senha!");
            return false;
        }
        String s1 = jTextField1.getText();
        String s2 = jTextField2.getText();
        if(!s1.equals(s2)){
            this.showWarningMessage("Confirme a senha corretamente!");
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adminCheckBox;
    private javax.swing.JCheckBox agendaCheckBox;
    private javax.swing.JCheckBox agendamentoCheckBox;
    private javax.swing.JCheckBox atendimentoCheckBox;
    private javax.swing.JCheckBox cancelamentoCheckBox;
    private javax.swing.JCheckBox convenioCheckBox;
    private javax.swing.JCheckBox especialidadeCheckBox;
    private javax.swing.JCheckBox funcionarioCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JCheckBox medicoCheckBox;
    private javax.swing.JCheckBox pacienteCheckBox;
    private javax.swing.JCheckBox usuarioCheckBox;
    // End of variables declaration//GEN-END:variables
}
